# Generated by Django 6.0.5 on 2026-06-22 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0002_conceptocotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='cotizaciones.cotizacion')),
            ],
        ),
    ]
