# Generated by Django 6.0.5 on 2026-07-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_conceptocotizacion_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptocotizacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='conceptocotizacion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='conceptocotizacion',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='conceptocotizacion',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='conceptocotizacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='conceptocotizacion',
            name='modificado_por',
        ),
    ]
